### ISSUE TITLE
Linter: Handle missing livecode-server more gracefully

### ISSUE THREAD

**Issue by peter-b** [peter-b/atom-language-livecode#10]
Currently, if there's no `livecode-server` in the `$PATH` and the user hasn't configured package, opening a `.livecodescript` file triggers a scary uncaught exception error.

The exception should be caught and an informational warning should be shown, directing users to the settings.

Probably another one for @montegoulding?

**Comment by montegoulding** [comment]
I'll see what I can come up with. It is documented that it needs to be accessible so I guess silently failing would be sufficient.

**Comment by montegoulding** [comment]
@peter-b I separated these commits so you could decide on the behavior you want to pull. The warning is nice but could be annoying if you didn't want to use the linter.. Although I wonder why you would have the linter package installed and yet not want to use it on livecode files...
