### ISSUE TITLE
Add grammar for livecode "scripts" themselves

### ISSUE THREAD

**Issue by alexchandel** [peter-b/atom-language-livecode#15]
Although there's no common extension, the scripts of LiveCode objects have similar but distinct grammars from the two you provide. Could you add their grammar as well? For now, it would probably be the job of the user to specify a custom file extension for this grammar, or else to manually select it, but it would be a huge improvement over just using the "AppleScript" grammar for editing LiveCode scripts that have been saved outside of stacks.

**Comment by peter-b** [comment]
The latest version of the package (0.6.x) supports script-only stacks (.livecodescript files) with the grammar for LiveCode objects. :+1:
