### ISSUE TITLE
LiveCode Script snippet behaviour is really annoying

### ISSUE THREAD

**Issue by peter-b** [peter-b/atom-language-livecode#17]
1) Create a new file and put it in LiveCode Script mode

2) Type `local tVar` <Enter>

3) Atom fills in some rubbish relating to `traversalOn`

This makes the Atom mode pretty unusable without perpetual <Escape>-mashing.

**Comment by peter-b** [comment]
@montegoulding I'd appreciate some input on this.  We can't default to "broken".

**Comment by montegoulding** [comment]
Hmm... have you changed your autocomplete-plus settings to confirm on enter?

**Comment by montegoulding** [comment]
I think this is not a bug. If you have the autocomplete setting to confirm on enter then that's what it should do. The fix to #18 makes autocomplete behave itself in a far more reasonable manner.

**Comment by peter-b** [comment]
@montegoulding Fair enough.  It does seem really annoying that autocomplete fires on things that aren't even matches, but never mind!
