### ISSUE TITLE
LiveCode Script auto-completion doesn't offer local symbols

### ISSUE THREAD

**Issue by peter-b** [peter-b/atom-language-livecode#18]
In LiveCode Script mode, the autocomplete settings don't result in useful suggestions.

---

In LiveCode Builder mode:

```
handler TestHandler()
    variable tTempVar

end handler
```

Put the cursor on the blank line and type `tte`.  The first suggestion is `tTempVar`.

---

In LiveCode Script mode:

```
on mouseUp
   local tTempVar

end mouseUp
```

Put the cursor on the blank line and type `tte`. The first suggestion is `templateEPS` and `tTempVar` doesn't appear anywhere in the suggested completions.

**Comment by montegoulding** [comment]
Hmm... any suggestions as to why this happens. I would have thought that suggestions from the local file would override any snippets

**Comment by montegoulding** [comment]
I've got it. PR coming soon.
