### ISSUE TITLE
The documentation should be structured better

### ISSUE THREAD

**Issue by peter-b** [peter-b/atom-language-livecode#19]
The top-level README file (which is also shown on [the package page](https://atom.io/packages/language-livecode)) needs to be more helpful.  Specifically:
- Installation instructions need to be more prominent, and need to link to the Atom documentation for "how to install packages". Optional dependency packages need to be listed with links to the appropriate packages' pages.
- Add links to the package pages and/or documentation for Atom features that the package integrates with, including indentation, auto-completion, snippets, and linting.
- Provide _very basic_ instructions for downloading/extracting LiveCode Server for LCS linting support.

**Comment by peter-b** [comment]
Given the feedback on the 0.6.0 release our documentation is unclear enough to basically be a bug. :sob:

**Comment by montegoulding** [comment]
One option would be to include the server engine in the package so it works out of the box. It does mean maintaining that though.

**Comment by peter-b** [comment]
@montegoulding I don't think that it's very practical to include the server engine in the package :fearful:!  I think the correct thing here is to make the server engine easier to install into the system path, possibly by proving both "Install Shell Commands" and "Install LiveCode Server" functions in the IDE somewhere.  I've been meaning to file an IDE feature request for a while, so I'll make that a higher priority.

**Comment by montegoulding** [comment]
Yes please!

**Comment by peter-b** [comment]
@montegoulding livecode/livecode-ide#612
