### ISSUE TITLE
If Upper/lowercase is important, then make sure that Variable Types Render Properly

### ISSUE THREAD

**Issue by macMikey** [peter-b/atom-language-livecode#29]
• both "List" and "list" render as variable types
• As an aside, "Number" and "Numbert" both render as variable types

**Comment by peter-b** [comment]
- Both `Number` and `Numbert` could be types, if you imported a module that defined a `Numbert` type.  I define a lot of custom types in some of the weirder LCB code that I write and I'd like them to carry on showing up as types.
- In contexts where it's unambiguous, `list` is a synonym for `List`.

I'm afraid at the moment I can't really see any alternative to keeping the syntax highlighting the way it is.  LCB is currently _partially_ case-sensitive, and most editors don't cope with this very well (indeed, neither do they cope well with the fact that LCB has a grammar that can't be expressed using regular expressions).
