### ISSUE TITLE
Error with "missing module atom-linter" when opening Atom

### ISSUE THREAD

**Issue by peter-b** [peter-b/atom-language-livecode#8]
With #7 merged in, opening atom causes an error message:

> Failed to activate the language-livecode package
> 
> Cannot find module 'atom-linter'

This is despite installing the [linter](https://atom.io/packages/linter) package.  So, either our README is wrong (and I need to install something else) or there's some other problem...

@montegoulding: any ideas?

**Comment by montegoulding** [comment]
The issue is the atom-linter node module. Because you're not a user getting the update installed by the package manager you need to `apm install` on the package. Then periodically `apm update` to get the latest version.

**Comment by peter-b** [comment]
Aha! Thank you, that fixed it!
